# docker-compose.yaml
version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: streamflow_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyc_taxi
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
